apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: dev-apps
  namespace: podinfo
spec:
  interval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: ./app/dev
  prune: true
  validation: client
