apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: global-cluster-addons
  namespace: flux-system
spec:
  interval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: eks-clusters-stack
  path: ./infrastructure/cluster-addons
  prune: true
  validation: client